# Generated by Django 4.2.3 on 2023-07-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="players",
            options={"verbose_name": "Player"},
        ),
        migrations.AddField(
            model_name="players",
            name="previous_club",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
